### ISSUE TITLE
Highlight E-Mail address

### ISSUE THREAD

**Issue by EPajares** [EPajares/meta-accessibility#1]
![Unbenannt](https://user-images.githubusercontent.com/42171996/72325868-549ce800-36ae-11ea-8b56-794ad4a1581d.PNG)

It would be could to highlight the E-Mail address in another color. Maybe blue?

**Comment by ivanchromjak** [comment]
Done ![Meta_Accessibility](https://user-images.githubusercontent.com/2057187/72522894-48d33200-3824-11ea-81c0-d18a4df04d06.png)

**Comment by EPajares** [comment]
Thanks
