### ISSUE TITLE
Show better which category is selected

### ISSUE THREAD

**Issue by EPajares** [EPajares/meta-accessibility#2]
![Unbenannt1](https://user-images.githubusercontent.com/42171996/72326010-9d54a100-36ae-11ea-89b5-b1592c331e6c.PNG)

So far it is not really visible to the user. which category he has selected. I think we need to highlight the selected category.

**Comment by ivanchromjak** [comment]
Done, just changed to the primary color, we could also add underline if needed 
![Meta_Accessibility](https://user-images.githubusercontent.com/2057187/72523568-b764bf80-3825-11ea-8233-52473e3e5376.png)

**Comment by EPajares** [comment]
I would say it is better now. Though I think it would be good if the user also can unselect a certain category. Let's say he click on walking again and again all modes are shown.

On another website I have seen it like this:
![Auswahl_084](https://user-images.githubusercontent.com/42171996/72530150-084cd600-386f-11ea-9406-ce1fee45360c.png)

Could we also try it?

**Comment by ivanchromjak** [comment]
@EPajares  Clicking the same link multiple times is may not be the most user-intuitive way about this and the component doesn't support it so we would need to hack it. A fairly easy alternative would be similar to your screenshot above when walking is selected/active it will display a cross icon on the right, when user clicks the icon the category mode will reset, what do you think?

**Comment by EPajares** [comment]
Sounds like it is worth trying it. Could you kindly try it.

**Comment by ivanchromjak** [comment]
@EPajares implemented, let me know your thoughts

**Comment by EPajares** [comment]
Looks almost perfect. But could you put the "x" a bit closer to the categories and make the "x" a bit bolder.
![Auswahl_088](https://user-images.githubusercontent.com/42171996/73732240-1f7a3780-473a-11ea-8280-06b2590fddfd.png)

**Comment by ivanchromjak** [comment]
@EPajares done

**Comment by EPajares** [comment]
Perfect! Thank you Ivan.
