### ISSUE TITLE
Test to restructure categorization

### ISSUE THREAD

**Issue by EPajares** [EPajares/meta-accessibility#3]
![Unbenannt3](https://user-images.githubusercontent.com/42171996/72326238-1e139d00-36af-11ea-9714-68d214f2b058.PNG)

If there are many categories that belong to one tool, this categorzation section can get a bit messy. It would be good to elaborate if it is possible to restructure it.

**Comment by ivanchromjak** [comment]
Improved 
![Meta_Accessibility](https://user-images.githubusercontent.com/2057187/72525831-a9656d80-382a-11ea-91e5-9845c0aaf2af.png)

**Comment by EPajares** [comment]
I think it is fine for now. Thank you!
