### ISSUE TITLE
Add Imprint & Privacy

### ISSUE THREAD

**Issue by EPajares** [EPajares/meta-accessibility#4]

**Comment by EPajares** [comment]
I will deliver content

**Comment by EPajares** [comment]
https://github.com/EPajares/meta-accessibility/blob/master/privacy_en

Here I have the content that should fit into the Imprint & Privacy. @ivanchromjak  Could you kindly create the page based on this content.

**Comment by ivanchromjak** [comment]
@EPajares privacy page added https://epajares.github.io/meta-accessibility/imprint-privacy-policy/

**Comment by EPajares** [comment]
Great. Thank you. It is fine like this
