### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by EPajares** [EPajares/meta-accessibility#6]

**Comment by EPajares** [comment]
I will deliver content

**Comment by EPajares** [comment]
The Meta-Accessibility website is based on the rich experiences gathered within the COST Action TU1002 on Accessibility Instruments for Planning Practice. The aim was and still is to close the gap between academia and practice. For this reason 24 accessibility instruments were collected, categorized and analyzed. Within local workshops practitioners rated the usefulness and usability of these accessibility instruments for their respective planning issues. Detailed information and reports can be found here: (add link to /cost-action-tu1002/)

Maybe it is possible to embed this image:
![image](https://user-images.githubusercontent.com/42171996/73339615-6fa85400-4279-11ea-9068-9715d6751073.png)


The Meta Accessibility website was developed and is run by the Research Group on Accessibility Planning at Technical University of Munich. We aim for integrated land-use and transport planning. Accessibility has been a proven concept enabling quality of life and sustainability in our cities. Accessibility instruments empowers interdisciplinary and cross-sectoral discussions among stakeholders and decision-makers. That is why we are keen about collecting and categorizing accessibility instruments in a transparent and open platform which enables networking. Feel free to submit your instrument here. Please do not hesitate to contact us (benjamin.buettner@tum.de), if you want to learn more about the Meta-Accessibility platform.

**Some more text will enter here:**

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

**Another picture should enter here: Please use a placeholder for now.**

**Comment by EPajares** [comment]
This is the image that was missing. So there is no placeholder needed.

![research_group_ap](https://user-images.githubusercontent.com/42171996/73664037-02445b00-469f-11ea-948b-440341aee729.jpg)

**Comment by EPajares** [comment]
@ivanchromjak Could you also do theis page

**Comment by ivanchromjak** [comment]
@EPajares about page content added

**Comment by EPajares** [comment]
Great thank you. I think we should use a bit more of the width. I think it could have the same width as the COST ACTION TU1002 page. 

Furthermore I think we should make the image (especially the first one a bit smaller).

**Comment by ivanchromjak** [comment]
@EPajares modified, if we want the images even smaller we could use more content to wrap around them

**Comment by EPajares** [comment]
Great. I think for now it is fine!
