### ISSUE TITLE
Add visitor log using Matomo

### ISSUE THREAD

**Issue by EPajares** [EPajares/meta-accessibility#8]

**Comment by EPajares** [comment]
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.open-accessibility.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '2']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by EPajares** [comment]
![Auswahl_090](https://user-images.githubusercontent.com/42171996/73763878-5d934d80-4772-11ea-8030-faf218929a24.png)

@ivanchromjak according to the docs we have to add this to every page. I guess we can put it somewhere in head section of our theme right?

**Comment by ivanchromjak** [comment]
@EPajares done, added in the header tag

**Comment by EPajares** [comment]
Great!
